hash-format = "sha256"

[[files]]
file = "config/advancementinfo.json5"

[[files]]
file = "config/animatica.properties"

[[files]]
file = "config/betterf3.json"

[[files]]
file = "config/builtinservers.json"

[[files]]
file = "config/capes.json5"

[[files]]
file = "config/cem.conf"

[[files]]
file = "config/citresewn.json"

[[files]]
file = "config/colormatic.properties"

[[files]]
file = "config/continuity.json"

[[files]]
file = "config/crowdin.txt"

[[files]]
file = "config/cullleaves.json"

[[files]]
file = "config/custom-fog.json"

[[files]]
file = "config/dashloader.yaml"

[[files]]
file = "config/durabilityviewer.json"

[[files]]
file = "config/dynamicfps.toml"

[[files]]
file = "config/enhanced_bes.properties"

[[files]]
file = "config/entityculling.json"

[[files]]
file = "config/fabric/indigo-renderer.properties"

[[files]]
file = "config/fabric_loader_dependencies.json"

[[files]]
file = "config/fabrishot.properties"

[[files]]
file = "config/fallingleaves.json"

[[files]]
file = "config/fast-chest.properties"

[[files]]
file = "config/ferritecore.mixin.properties"

[[files]]
file = "config/gamecontrollerdb.txt"

[[files]]
file = "config/hdskins.json"

[[files]]
file = "config/illuminations.properties"

[[files]]
file = "config/indium-renderer.properties"

[[files]]
file = "config/inventoryprofilesnext/ModIntegrationHints.json"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"

[[files]]
file = "config/iris.properties"

[[files]]
file = "config/itemmodelfix.json"

[[files]]
file = "config/lambdabettergrass.toml"

[[files]]
file = "config/lambdacontrols.toml"

[[files]]
file = "config/lambdynlights.toml"

[[files]]
file = "config/lightoverlay.properties"

[[files]]
file = "config/lithium.properties"

[[files]]
file = "config/midnightlib.json"

[[files]]
file = "config/minelp.json"

[[files]]
file = "config/moderate-loading-screen.json5"

[[files]]
file = "config/modmenu.json"

[[files]]
file = "config/multiconnect/caches/1.17.1/1.17.1.json"

[[files]]
file = "config/multiconnect/caches/1.17.1/1.17.1.json.etag"

[[files]]
file = "config/multiconnect/caches/1.17.1/en_gb.lang"

[[files]]
file = "config/multiconnect/caches/1.17.1/en_gb.lang.etag"

[[files]]
file = "config/multiconnect/caches/1.17.1/indexes.json"

[[files]]
file = "config/multiconnect/caches/1.17.1/indexes.json.etag"

[[files]]
file = "config/multiconnect/caches/1.18/1.18.json"

[[files]]
file = "config/multiconnect/caches/1.18/1.18.json.etag"

[[files]]
file = "config/multiconnect/caches/1.18/en_gb.lang"

[[files]]
file = "config/multiconnect/caches/1.18/en_gb.lang.etag"

[[files]]
file = "config/multiconnect/caches/1.18/indexes.json"

[[files]]
file = "config/multiconnect/caches/1.18/indexes.json.etag"

[[files]]
file = "config/multiconnect/caches/version_manifest.json"

[[files]]
file = "config/multiconnect/caches/version_manifest.json.etag"

[[files]]
file = "config/multiconnect/servers_ext.json"

[[files]]
file = "config/notenoughcrashes.json"

[[files]]
file = "config/presencefootsteps/updater.json"

[[files]]
file = "config/presencefootsteps/userconfig.json"

[[files]]
file = "config/quantumfusion/dashloader/mods-10ebb/1-registry.serializer"

[[files]]
file = "config/quantumfusion/dashloader/mods-10ebb/2-model.serializer"

[[files]]
file = "config/quantumfusion/dashloader/mods-10ebb/3-image.serializer"

[[files]]
file = "config/quantumfusion/dashloader/mods-10ebb/4-mapping.serializer"

[[files]]
file = "config/quantumfusion/dashloader/mods-10ebb/resourcepacks-1593/mappings-data.activej"

[[files]]
file = "config/quantumfusion/dashloader/mods-10ebb/resourcepacks-1593/registry-data.activej"

[[files]]
file = "config/quantumfusion/dashloader/mods-10ebb/resourcepacks-1593/registry-image-data.activej"

[[files]]
file = "config/quantumfusion/dashloader/mods-10ebb/resourcepacks-1593/registry-model-data.activej"

[[files]]
file = "config/replaymod.json"

[[files]]
file = "config/rrp.properties"

[[files]]
file = "config/shulkerboxtooltip.json5"

[[files]]
file = "config/slightguimodifications/config.json5"

[[files]]
file = "config/slightguimodifications/cts.groovy"

[[files]]
file = "config/smoothboot.json"

[[files]]
file = "config/sodium-extra-options.json"

[[files]]
file = "config/sodium-mixins.properties"

[[files]]
file = "config/sodium-options.json"

[[files]]
file = "config/waterdripsound.json"

[[files]]
file = "config/yosbr/config/capes.json5"

[[files]]
file = "config/yosbr/config/cullleaves.json"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"

[[files]]
file = "config/yosbr/config/iris.properties"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"

[[files]]
file = "config/yosbr/config/modmenu.json"

[[files]]
file = "config/yosbr/config/slightguimodifications/config.json5"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"

[[files]]
file = "config/yosbr/config/sodium-options.json"

[[files]]
file = "config/yosbr/options.txt"

[[files]]
file = "mods/advancementinfo.toml"
metafile = true

[[files]]
file = "mods/animatica.toml"
metafile = true

[[files]]
file = "mods/antighost.toml"
metafile = true

[[files]]
file = "mods/architectury-fabric.toml"
metafile = true

[[files]]
file = "mods/better-mount-hud.toml"
metafile = true

[[files]]
file = "mods/betterf3.toml"
metafile = true

[[files]]
file = "mods/builtin-servers.toml"
metafile = true

[[files]]
file = "mods/capes.toml"
metafile = true

[[files]]
file = "mods/cit-resewn.toml"
metafile = true

[[files]]
file = "mods/cloth-api.toml"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
metafile = true

[[files]]
file = "mods/colormatic.toml"
metafile = true

[[files]]
file = "mods/completeconfig.toml"
metafile = true

[[files]]
file = "mods/continuity.toml"
metafile = true

[[files]]
file = "mods/cull-leaves.toml"
metafile = true

[[files]]
file = "mods/custom-entity-models-cem.toml"
metafile = true

[[files]]
file = "mods/dripsounds-fabric.toml"
metafile = true

[[files]]
file = "mods/durabilityviewer.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.toml"
metafile = true

[[files]]
file = "mods/ears.toml"
metafile = true

[[files]]
file = "mods/ebe.toml"
metafile = true

[[files]]
file = "mods/entityculling.toml"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
metafile = true

[[files]]
file = "mods/fabricskyboxes.toml"
metafile = true

[[files]]
file = "mods/fabrishot.toml"
metafile = true

[[files]]
file = "mods/fallingleaves.toml"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.toml"
metafile = true

[[files]]
file = "mods/hd-skins.toml"
metafile = true

[[files]]
file = "mods/indium.toml"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.toml"
metafile = true

[[files]]
file = "mods/iris.toml"
metafile = true

[[files]]
file = "mods/item-model-fix.toml"
metafile = true

[[files]]
file = "mods/kappa.toml"
metafile = true

[[files]]
file = "mods/krypton.toml"
metafile = true

[[files]]
file = "mods/lambdabettergrass.toml"
metafile = true

[[files]]
file = "mods/lambdacontrols.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.toml"
metafile = true

[[files]]
file = "mods/language-reload.toml"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
metafile = true

[[files]]
file = "mods/light-overlay.toml"
metafile = true

[[files]]
file = "mods/lithium.toml"
metafile = true

[[files]]
file = "mods/logical-zoom.toml"
metafile = true

[[files]]
file = "mods/mine-little-pony.toml"
metafile = true

[[files]]
file = "mods/moderate-loading-screen.toml"
metafile = true

[[files]]
file = "mods/modmenu.toml"
metafile = true

[[files]]
file = "mods/more-chat-history.toml"
metafile = true

[[files]]
file = "mods/multiconnect.toml"
metafile = true

[[files]]
file = "mods/no-telemetry.toml"
metafile = true

[[files]]
file = "mods/notenoughcrashes.toml"
metafile = true

[[files]]
file = "mods/presence-footsteps.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.toml"
metafile = true

[[files]]
file = "mods/replaymod.toml"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.toml"
metafile = true

[[files]]
file = "mods/slight-gui-modifications.toml"
metafile = true

[[files]]
file = "mods/smooth-boot.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.toml"
metafile = true

[[files]]
file = "mods/sodium.toml"
metafile = true

[[files]]
file = "mods/starlight.toml"
metafile = true

[[files]]
file = "mods/tooltipfix.toml"
metafile = true

[[files]]
file = "mods/yosbr.toml"
metafile = true

[[files]]
file = "options.txt"

[[files]]
file = "shaderpacks/BSL_v8.1.01.zip"

[[files]]
file = "shaderpacks/ComplementaryShaders_v4.2.2.zip"

[[files]]
file = "shaderpacks/Sildur's+Vibrant+Shaders+v1.30+Extreme-Volumetric-Lighting.zip"

[[files]]
file = "shaderpacks/Sildur's+Vibrant+Shaders+v1.30+Extreme.zip"

[[files]]
file = "shaderpacks/Sildur's+Vibrant+Shaders+v1.30+High.zip"

[[files]]
file = "shaderpacks/Sildur's+Vibrant+Shaders+v1.30+Lite.zip"

[[files]]
file = "shaderpacks/Sildur's+Vibrant+Shaders+v1.30+Medium.zip"
