name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de18ded7c3b5a19b7aa728b22647372172a1545b80d0eb092154742167a53538"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
