name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38034204d473f5721189869071eca02a15af1d70be38dfe1990b1521bda74553"

[versions]
fabric = "0.12.8"
minecraft = "1.18"

[options]
acceptable-game-versions = "1.18-rc4"
no-internal-hashes = false
