name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.4.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54ffef24b028f3281950593033acdb387ec2d9247902b9e6a38e00f447059d58"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
no-internal-hashes = false
