name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.4.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccc0d21cab4b4ad33fd84f54530496ef4dea0639c486a9878a228f8119248ba7"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
