name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.4.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db3630442919df94a38c91d1203115aa6a3893b39710d404fb5df09327b122cb"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
