name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.4.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e8c6c3ae4f83736c8d94f6dd1f2f3844a67dfe92b23550eb397c5d24eedf4b3"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
