name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a90bf098dbac517c17ae2a87872b1ffa594098776c14dea45d0c3496ae9bb29e"

[versions]
fabric = "0.12.8"
minecraft = "1.18"

[options]
acceptable-game-versions = "1.18-rc4"
no-internal-hashes = false
