name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89b81fa7dd8454dd286371c86db026fcb04c32c3bb36cc39a63c3fd3d7574bfe"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
