name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31536704e22c43defb98aaa02e21fd6d3678bd59d01337b6f6d5b43c91bf54ba"

[versions]
fabric = "0.12.5"
minecraft = "1.18"

[options]
acceptable-game-versions = "1.18-rc4"
no-internal-hashes = false
