name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e68afaf67e9e7ee122f510215dbb8b1532c47565f7cd2fbbc38baf287471ea80"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
