name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.4.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b08a30f26db5bb4ebb97902bc977c0598953d482231d63ffb25194b2ef586df4"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
no-internal-hashes = false
