name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41c21778851070a4626a74c53ec0c2f1c6cff745559c69695fa7e4673f567700"

[versions]
fabric = "0.14.7"
minecraft = "1.19"

[options]
no-internal-hashes = false
