name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63250892c290c894f633905e5e9f0e71ad5825aaa1de855fd123d15690147c72"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
