name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4be2f5593100b19d935dfb2a62a68885d467dbf00ade5c97effc5598f320f1d"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
