name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50ed40b5c4aa7e067e05569ba881e3d2d2a93944e4d3b113909db5867bdd5e5f"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
