name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f94787ea444cc14a9de64ee6383f79ce2fa9bbb9e163aa9173215477d4477e2e"

[versions]
fabric = "0.12.5"
minecraft = "1.18"

[options]
acceptable-game-versions = "1.18-rc4"
no-internal-hashes = false
