name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "501a59d75fc3511f2210d664e93ef67d8cb93852b01197f450d1848aa6bcf3db"

[versions]
fabric = "0.12.5"
minecraft = "1.18"

[options]
acceptable-game-versions = "1.18-rc4"
no-internal-hashes = false
