name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cab0643a5b19f71bfc0b9b1cd660b7dde7c822af6bd34aeaad9fceb4bf8f28c"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
