name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8403a8050b694dc3d9c48e5755e39ee4e8a7fcc128fb4e40a061558296f00d49"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
