name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0738ec5d46517de4042b2f6b5c400acf978d9cf499ba663e69e3fc562caafae0"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
