name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19f697e57e72ee758d2367dd0f14f6a16e68c11bd790a176a7a630a89003ab05"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
