name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c7b41e17daf650d0bda9ae6f23db1f1327df275216734fe21e2192d2c68c3e5"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
