name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34c3bb3aabbaf64d6ff4010d41b13402ff2639dcce9e46166b2acb5ef588f12b"

[versions]
fabric = "0.12.9"
minecraft = "1.18"

[options]
acceptable-game-versions = "1.18-rc4"
no-internal-hashes = false
