name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.4.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e87c168222558fcac5312598c4caa47f07fd15893c127d02a9e1f3b51afc03f2"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
