name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a42fe33b520e1dff05015ecfadcd6cedfc3d88599923ac8ce690712f4663bba"

[versions]
fabric = "0.12.9"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
no-internal-hashes = false
