name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad44ef0d5fc2ce3c381d717b047fd64e6030d7f0cadeb5db75fbf42c31b31256"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
