name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.4.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9d5df6333c4292458a639429bc32c072e57fd1730b3f127fd0fd31460e7bf1b"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
no-internal-hashes = false
