name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.4.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32d6ac9461a06cc2b5e5c433dbeb14fb24351f558dd7aaa01e51e624fcd0a5b1"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
