name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dcc90a69a4255109ddfeba809f27eeae8696553750d36a0c657318fccaa1c74"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
no-internal-hashes = false
