name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.4.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0534aa26ee221e180f4ae928bae6ba68eea1a1ba67e8f245ba6a586c09b2b482"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
