name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2fd57109d72ca671747a3fa63b9ddb3b3f8811e07a7a1b24c41d5d5a0cf7737"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
