name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3574409d5d46d2d7474e46dc1f5ac871f915f81168fbb92667956b5303498b3d"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
