name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "549b8719893241aae15f46a91b29adeea4b49eba9f72f990497bf9fe213d64c7"

[versions]
fabric = "0.12.5"
minecraft = "1.18"

[options]
acceptable-game-versions = "1.18-rc4"
no-internal-hashes = false
