name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.4.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7b3c7e81623a4fe5a69eb4348c5a624462223a3048675f54cd79590d03973a9"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
no-internal-hashes = false
