name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6f22cba92804ba86b366ed69658224f2b3b511a40aea6f600e219fd42f7e977"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
