name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.5.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bcc732f62b8c4fb56fcea1629b1dc12e286bbc120b981f85ef8c49c683a38b3"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"

[options]
no-internal-hashes = false
