name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c0e004bcdc3da9879ee6bf1be25c2f03c07a516ce5c0b420c4874930e99601e"

[versions]
fabric = "0.12.9"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
no-internal-hashes = false
