name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d07ceaef5654416b98b0a75858d1da034295f839966a665a96ba5614beead9d4"

[versions]
fabric = "0.12.5"
minecraft = "1.18"

[options]
no-internal-hashes = false
