name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bb16cd6fc16d66645dd07f054ba37f679859146859eae0dd06fb8513b07ea4e"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
