name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c7cf57c4eaa3177a94c24edd78e873b26859764d39c50a037df2f35376e6561"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
