name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.4.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "097ae0e38f7a4113967733379118205e25aef7e78171dd4844fe8ec2e80830f5"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
no-internal-hashes = false
