name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6683ae83194d4365afb96bbbc1233eb74f08e64596aba4bdcf72b63df74dc2e"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
