name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27bfcf4fee0e37c26b00c2d3f7c1df1fc25132028d192b1ac2a63619336ba1f3"

[versions]
fabric = "0.12.9"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
