name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "446151008e89c06bcfee7467cb3a2af112ecee1ada6bae1975a97eb6d440a94d"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"

[options]
no-internal-hashes = false
