name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f95d9a68cbc487d8516dfdb48aee660d5193d0f445d49de63541526dbfc2f37"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
