name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfa3c56290368c7f246542707d9ff8ac557d5967bb2959d5cd302a939e89efb0"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
