name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3213eb9d574fc75aa720c8eb8e38f7f882d2990bf704b8a925aed10811e515ef"

[versions]
fabric = "0.12.9"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
no-internal-hashes = false
