name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "2.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d85c85d5f80fd4356389e96b57142d0083cd473d6d801168e6895b73702ddcac"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
