name = "Techtastisch Comunity Modpack"
author = "Fauli1221"
version = "1.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "980fee2b7b69d2b83b66f02f5ce5d02b9dced3be5a9cd470f0954008757216cf"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
