name = "Animatica"
filename = "animatica-0.4+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3664/303/animatica-0.4+1.18.jar"
hash-format = "murmur2"
hash = "3520632105"

[update]
[update.curseforge]
file-id = 3664303
project-id = 533006
