name = "Architectury API (Fabric/Forge)"
filename = "architectury-4.4.59.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3784/130/architectury-4.4.59.jar"
hash-format = "sha1"
hash = "3c8a475c5e28d8e4ce7aff81c317d82fdc7ceb66"

[update]
[update.curseforge]
file-id = 3784130
project-id = 419699
