name = "Architectury API (Fabric)"
filename = "architectury-2.8.67.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3587/94/architectury-2.8.67.jar"
hash-format = "murmur2"
hash = "2288875140"

[update]
[update.curseforge]
file-id = 3587094
project-id = 419697
release-channel = "beta"
