name = "Architectury API (Fabric)"
filename = "architectury-3.0.37.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3507/237/architectury-3.0.37.jar"
hash-format = "murmur2"
hash = "3103125272"

[update]
[update.curseforge]
file-id = 3507237
project-id = 419697
