name = "Architectury API (Fabric)"
filename = "architectury-3.2.56.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3573/781/architectury-3.2.56.jar"
hash-format = "murmur2"
hash = "1779510533"

[update]
[update.curseforge]
file-id = 3573781
project-id = 419697
