name = "BetterF3"
filename = "BetterF3-1.2.3-Fabric-1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/8shC1gFX/versions/1.2.3/BetterF3-1.2.3-Fabric-1.18.2.jar"
hash-format = "sha512"
hash = "56fb743a0899223b7260ae8092a5c15ae95b2b5e1bb74ddc236b4e46dfdf80afc93f0d175fceddca0360153858c87fc9c5264b637399d6dd55223b7729cf3e68"

[update]
[update.modrinth]
mod-id = "8shC1gFX"
version = "FkuTWPSR"

[option]
optional = true
description = "BetterF3 is a mod that replaces Minecraft's original debug HUD with a highly customizable, more human-readable HUD."
