name = "Big Pony"
filename = "bigpony-1.6.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/h9pJxJR9/versions/1.6.2/bigpony-1.6.2.jar"
hash-format = "sha512"
hash = "0d70d76bd39f36e7cc304d8caa1e136fe23c93cef5eaebaca8df437faab412ca30d9b098df63dc38f1fd5a9f9c86083caa7cdf596468f19cb5991285cef3811c"

[update]
[update.modrinth]
mod-id = "h9pJxJR9"
version = "8AB8Nfx1"

[option]
optional = true
description = "Adds hitbox Scaling for MineLittlePony (DO NOT ENABLE UNLESS I TELL YOU TO)"
