name = "Big Pony"
filename = "bigpony-1.6.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/h9pJxJR9/versions/1.6.1/bigpony-1.6.1.jar"
hash-format = "sha512"
hash = "e9c06d3b4b6a94f85e0fdb06e4adfdf5c4f3dede1976fe6eff61b4567c2a9f338061f436039451762362c9d4cc6440eab9d8ac170725c334d748b14a30a2a9ec"

[update]
[update.modrinth]
mod-id = "h9pJxJR9"
version = "HcOEBEkx"

[option]
optional = true
description = "Adds hitbox Scaling for MineLittlePony (DO NOT ENABLE UNLESS I TELL YOU TO)"
