name = "Builtin Servers"
filename = "builtin-servers-1.0.1-BETA+1.18.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/IupkwRPf/versions/1.0.1-BETA+1.18/builtin-servers-1.0.1-BETA+1.18.jar"
hash-format = "sha512"
hash = "77320db1878f0359b863c2f54a6510f9c3eb9ea5575f798759d68666533ce3d5072f15da471a029551cfda3b7c438980d8dcf79c46b63f8f7f40ff5a17b34829"

[update]
[update.modrinth]
mod-id = "IupkwRPf"
version = "XmmlrtGC"
