name = "Cloth Config API (Fabric)"
filename = "cloth-config-6.0.42-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3524/837/cloth-config-6.0.42-fabric.jar"
hash-format = "murmur2"
hash = "754092429"

[update]
[update.curseforge]
file-id = 3524837
project-id = 319057
