name = "Cloth API (Fabric)"
filename = "cloth-api-3.1.58.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3609/860/cloth-api-3.1.58.jar"
hash-format = "murmur2"
hash = "2641392162"

[update]
[update.curseforge]
file-id = 3609860
project-id = 317121
