name = "Colormatic"
filename = "colormatic-3.1.0+mc.1.18.1.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/V4IQxkZC/versions/3.1.0/colormatic-3.1.0%2Bmc.1.18.1.jar"
hash-format = "sha1"
hash = "7357a0a45aa4d00d06f52ba9cee643869ae25e40"

[update]
[update.modrinth]
mod-id = "V4IQxkZC"
version = "vwRKcfWe"
