name = "Durability Viewer"
filename = "durabilityviewer-1.18.2-fabric0.47.10-1.10.3.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/LTM1f0yY/versions/1.18.2-fabric0.47.10-1.10.3/durabilityviewer-1.18.2-fabric0.47.10-1.10.3.jar"
hash-format = "sha512"
hash = "40a59e9e4a471e85052aae638d9f533ec2ba41a82000852956b5d14cb53ed10ebbe1bac40ecd9079a799b4263964524a394d5f3ebceaf39ab2c72825698f1900"

[update]
[update.modrinth]
mod-id = "LTM1f0yY"
version = "FSC9nc1c"

[option]
optional = true
description = "adds an overlay to display your Durability"
