name = "Ears (+ Snouts/Muzzles, Tails, Horns, Wings, and More)"
filename = "ears-fabric-1.17-1.4.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3586/76/ears-fabric-1.17-1.4.4.jar"
hash-format = "murmur2"
hash = "3051093935"

[update]
[update.curseforge]
file-id = 3586076
project-id = 412013

[option]
optional = true
description = "Adds more skin cusomisations to the game that are targeted at furrys (can be ignored unless it bothers you)"
default = true
