name = "Entity Texture Features - [Fabric]"
filename = "entity-texture-features-beta-2.6.1-mc1.18+.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3773/590/entity-texture-features-beta-2.6.1-mc1.18+.jar"
hash-format = "murmur2"
hash = "1724069096"

[update]
[update.curseforge]
file-id = 3773590
project-id = 568563
