name = "Entity Texture Features - [Fabric]"
filename = "entity-texture-features-beta-2.6.3-mc1.18.x.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "9b75e5754e584fe3b343b2257f546f68f84a0b34"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3801379
project-id = 568563
