name = "Entity Texture Features - [Fabric]"
filename = "entity-texture-features-3.0.4-mc1.18.x.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "4372b8d99eb259f63bb81e99fb18598ccb52f7b7"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3814328
project-id = 568563
