name = "FabricSkyboxes"
filename = "fabricskyboxes-1.18.2-0.5.5.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YBz7DOs8/versions/0.5.5/fabricskyboxes-1.18.2-0.5.5.jar"
hash-format = "sha512"
hash = "2093b005255b6a09ceb1bd49c62625eed7b4ddd710880cb3ebce6a7a8eed069abfae9b5a854a30220d65fdf37d0703c431164d8e146349f607b3f142deadc5f1"

[update]
[update.modrinth]
mod-id = "YBz7DOs8"
version = "m8fbq5qt"
