name = "FancyMenu [Fabric]"
filename = "fancymenu_fabric_2.7.2-1_MC_1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "fe1aa8828a1cce128e5bb2b34e69924ed8445291"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3817570
project-id = 416796
