name = "FancyMenu [Fabric]"
filename = "fancymenu_fabric_2.7.2_MC_1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "42bbe5793695ef0562e2d3fa02958b8532ac7cc3"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3798418
project-id = 416796
