name = "FancyMenu [Fabric]"
filename = "fancymenu_fabric_2.6.4_MC_1.18-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/335/fancymenu_fabric_2.6.4_MC_1.18-1.18.1.jar"
hash-format = "murmur2"
hash = "3226318389"

[update]
[update.curseforge]
file-id = 3671335
project-id = 416796
