name = "FancyMenu [Fabric]"
filename = "fancymenu_fabric_2.6.4_MC_1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/337/fancymenu_fabric_2.6.4_MC_1.18.2.jar"
hash-format = "murmur2"
hash = "119977093"

[update]
[update.curseforge]
file-id = 3671337
project-id = 416796
