name = "FancyMenu [Fabric]"
filename = "fancymenu_fabric_2.7.0_MC_1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3777/826/fancymenu_fabric_2.7.0_MC_1.18.2.jar"
hash-format = "murmur2"
hash = "48846394"

[update]
[update.curseforge]
file-id = 3777826
project-id = 416796
