name = "HD Skins"
filename = "hdskins-6.5.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/FzE9gshV/versions/6.5.2/hdskins-6.5.2.jar"
hash-format = "sha512"
hash = "05b411d05cc51d93463e21ac43d700b271f4c72064f9240766e04d31810dd4549f3ed6f79ca94b0d255e2176fe5a527ca2cd1fb2ccdd58b85576aba66ab7aea4"

[update]
[update.modrinth]
mod-id = "FzE9gshV"
version = "O5qwHu2G"

[option]
optional = true
description = "Adds a custom skin server with HD-Skin support Recomendet with MineLittlePony"
default = true
