name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18-1.3.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/O7RBXm3n/versions/fabric-1.18.1-1.3.2/InventoryProfilesNext-fabric-1.18-1.3.2.jar"
hash-format = "sha512"
hash = "1d36311ac2314489f4e9d5798170417030f4dea3e43b1ab87a84e49c5764e9d82704f8ddac0aa60beee588a9b4165546ef4f88a555f31054013bdbd9c06dfbb3"

[update]
[update.modrinth]
mod-id = "O7RBXm3n"
version = "kVETFPjb"

[option]
optional = true
description = "Adds a button to sort Inventorys"
default = true
