name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.17-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3557/216/InventoryProfilesNext-fabric-1.17-1.2.1.jar"
hash-format = "murmur2"
hash = "337418854"

[update]
[update.curseforge]
file-id = 3557216
project-id = 495267
release-channel = "beta"
