name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.17-1.1.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3533/6/InventoryProfilesNext-fabric-1.17-1.1.7.jar"
hash-format = "murmur2"
hash = "2875512268"

[update]
[update.curseforge]
file-id = 3533006
project-id = 495267
release-channel = "beta"
