name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18-1.3.4.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/O7RBXm3n/versions/fabric-1.18.1-1.3.4/InventoryProfilesNext-fabric-1.18-1.3.4.jar"
hash-format = "sha512"
hash = "dd6e12a9bcaaa50a2525b77af7700662bc22405f5f252f5016e98a31d2cfff5f85905184410c12940cd285706861aa0b2e1411aae15c548616d6d3e78e3a627c"

[update]
[update.modrinth]
mod-id = "O7RBXm3n"
version = "xYkQJgk4"

[option]
optional = true
description = "Adds a button to sort Inventorys"
default = true
