name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.17-1.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3514/87/InventoryProfilesNext-fabric-1.17-1.1.3.jar"
hash-format = "murmur2"
hash = "2989477886"

[update]
[update.curseforge]
file-id = 3514087
project-id = 495267
release-channel = "beta"
