name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18.2-1.3.6.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/O7RBXm3n/versions/fabric-1.18.2-1.3.6/InventoryProfilesNext-fabric-1.18.2-1.3.6.jar"
hash-format = "sha512"
hash = "190c0b07d3d986c25ec73de6532cf7d3286d5a8f4754dedba9aeeda7cf143025952b4e90f8c41926f14aa5a91ccc7ecff5b62ffa5ef8bfef70bd5c75ee5b3cee"

[update]
[update.modrinth]
mod-id = "O7RBXm3n"
version = "G5BBMNPg"

[option]
optional = true
description = "Adds a button to sort Inventorys"
default = true
