name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.17-1.1.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3537/796/InventoryProfilesNext-fabric-1.17-1.1.8.jar"
hash-format = "murmur2"
hash = "3467854278"

[update]
[update.curseforge]
file-id = 3537796
project-id = 495267
release-channel = "beta"
