name = "Iris Shaders"
filename = "iris-mc1.18.2-1.2.4-build.38.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YL57xq9U/versions/1.18.x-v1.2.4/iris-mc1.18.2-1.2.4-build.38.jar"
hash-format = "sha512"
hash = "bed262d3bd08fe5f844d98c8eeff191adfa1bf141471d9f756dce9c10fdb87a55d26421f2a2f5bf8a4f90fbea9f3974470f41108d44dc468e2fdf0f3845ed61b"

[update]
[update.modrinth]
mod-id = "YL57xq9U"
version = "Onlo6jbu"

[option]
optional = true
description = "adds optifine shader support"
default = true
