name = "Light Overlay (Rift/Forge/Fabric)"
filename = "light-overlay-6.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3668/243/light-overlay-6.0.5.jar"
hash-format = "murmur2"
hash = "1459910646"

[update]
[update.curseforge]
file-id = 3668243
project-id = 325492

[option]
optional = true
description = "Adds a overlay over blocks mobs can spawn"
