name = "Mine Little Pony"
filename = "minelittlepony-4.4.4.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/JBjInUXM/versions/4.4.4/minelittlepony-4.4.4.jar"
hash-format = "sha512"
hash = "92534d411a982da5029f890beb275dbadf6353b8261870b0a1e678e1db185a7a6fdb095360ad1c1b03c0541910ef9a434953abc73972360f2fca501bd4e897a2"

[update]
[update.modrinth]
mod-id = "JBjInUXM"
version = "kbkztK7t"

[option]
optional = true
description = "Adds Pony's to the game"
default = true
