name = "MineLittlePony"
filename = "minelittlepony-4.3.8.jar"
side = "client"

[download]
url = "https://github.com/MineLittlePony/MineLittlePony/releases/download/4.3.8/minelittlepony-4.3.8.jar"
hash-format = "sha512"
hash = "952919a025ce3b2e88a18a487af02c015430b28aec2599f29b7cc84ca311977f85a43d35c77fef4f31bfeab7c209ce30076182acc8abd42f9d6ae6aff1f66b5c"

[option]
default = true
description = "Adds Pony's to the game"
optional = true
