name = "Mod-erate Loading Screen"
filename = "moderate-loading-screen-1.1.1+1.17-1.18.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/RCjGlCDj/versions/1.1.1/moderate-loading-screen-1.1.1+1.17-1.18.jar"
hash-format = "sha512"
hash = "20fa6bbbd46f98271dc7a83bf2382dccd35fc5e4cfa24ba0577df261ff183c6511bb7b38393588b81ab54e2f43fb7bf07b0ec41d1775b4582d064071b0ed463f"

[update]
[update.modrinth]
mod-id = "RCjGlCDj"
version = "SkAeSPCD"
