name = "multiconnect"
filename = "multiconnect-1.5.9.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/sfEDKnlo/versions/1.5.9/multiconnect-1.5.9.jar"
hash-format = "sha512"
hash = "919f469bb09b52c0fdb99c481aa92186c1df8e437ec03591d693b28f82cbfdc29390d66534c3241bef3443b46998002d5f2973e711cac92d4520f897bf30df27"

[update]
[update.modrinth]
mod-id = "sfEDKnlo"
version = "jPQL5bGk"
