name = "multiconnect"
filename = "multiconnect-1.5.3.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/sfEDKnlo/versions/1.5.3/multiconnect-1.5.3.jar"
hash-format = "sha512"
hash = "5a633e45220686c5b1897fdc832faef0ec6305bff6ad22354b5f4cdd98e80ff68d05272e6553e8af79c894c3236d5fe70241ddebb8a70532efc52780a19e9638"

[update]
[update.modrinth]
mod-id = "sfEDKnlo"
version = "IT2rAWiJ"
