name = "No Telemetry"
filename = "no-telemetry-1.2.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/hg77g4Pw/versions/1.2.0/no-telemetry-1.2.0.jar"
hash-format = "sha512"
hash = "5ba430ff1ce2b05c15d6ec353fecc66c533213d248e1e8ce0a22baf13165fdd7f6d9d8d7dda19631c74b62bb601edd624f354aaf6b443c10691e03f8e65f9cfe"

[update]
[update.modrinth]
mod-id = "hg77g4Pw"
version = "zZRdCapG"
