name = "Not Enough Crashes (Fabric)"
filename = "notenoughcrashes-3.6.3+1.17.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3474/233/notenoughcrashes-3.6.3+1.17.1-fabric.jar"
hash-format = "murmur2"
hash = "2042038442"

[update]
[update.curseforge]
file-id = 3474233
project-id = 353890
release-channel = "beta"
