name = "OF Capes"
filename = "fabric-optifine-capes-2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3347/407/fabric-optifine-capes-2.0.0.jar"
hash-format = "murmur2"
hash = "3390458128"

[update]
[update.curseforge]
file-id = 3347407
project-id = 407910
release-channel = "beta"
