name = "Old Walking Animaton"
filename = "old-walking-animation-1.1.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/qPhGj08K/versions/1.1.0/old-walking-animation-1.1.0.jar"
hash-format = "sha512"
hash = "edba3a8a1ef8619475f8a637c0baa3e63d5e5218b4b5aef5ee6fd2e0180a4ed309e0fbd2cf0952ca730aafeafb7bd5f09f868dc6affa2a5e5ba50d45008a4afb"

[update]
[update.modrinth]
mod-id = "qPhGj08K"
version = "oUGtgG9M"

[option]
default = false
description = "Brings back the walking animation from the Indev days of MC"
optional = true
