name = "OptiGUI"
filename = "optigui-1.0.4.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "9dc91c9f0e60d5abe6d13e901721535272a69857"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3786932
project-id = 619986
