name = "OptiGUI"
filename = "optigui-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3777/749/optigui-1.0.0.jar"
hash-format = "sha1"
hash = "22cc66f6fa14a829a9bfa83f79ad81e61055d507"

[update]
[update.curseforge]
file-id = 3777749
project-id = 619986
