name = "ShulkerBoxTooltip"
filename = "shulkerboxtooltip-3.0.6+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3684/24/shulkerboxtooltip-3.0.6+1.18.2.jar"
hash-format = "murmur2"
hash = "210747937"

[update]
[update.curseforge]
file-id = 3684024
project-id = 315811

[option]
optional = true
description = "adds an overlay to see into shulkerboxes"
