name = "Simple Discord RPC [Forge/Fabric]"
filename = "SimpleRPC-fabric-1.18.2-3.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3785/429/SimpleRPC-fabric-1.18.2-3.0.1.jar"
hash-format = "murmur2"
hash = "1987236581"

[update]
[update.curseforge]
file-id = 3785429
project-id = 411816
