name = "Simple Discord RPC [Forge/Fabric]"
filename = "simple-rpc-fabric-1.18.x-2.7.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3596/443/simple-rpc-fabric-1.18.x-2.7.1.jar"
hash-format = "murmur2"
hash = "273098465"

[update]
[update.curseforge]
file-id = 3596443
project-id = 411816
