name = "Smooth Boot (Fabric)"
filename = "smoothboot-fabric-1.18.2-1.7.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3692/365/smoothboot-fabric-1.18.2-1.7.0.jar"
hash-format = "murmur2"
hash = "3891973134"

[update]
[update.curseforge]
file-id = 3692365
project-id = 415758
