name = "TieFix"
filename = "TieFix-1.9.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/jxuxsA0D/versions/1.9.0/TieFix-1.9.0.jar"
hash-format = "sha512"
hash = "324dd9fcefcb05aca112c28053806847315e5a304db4fcaec0f5d5c4c032b1ed6f038aad92a81c603b92e9d200e56fd7cf3c66686ed3c9926d51c6c42bc3bad7"

[update]
[update.modrinth]
mod-id = "jxuxsA0D"
version = "7MP0Ay5i"
