name = "ViaFabric"
filename = "viafabric-0.4.7+3-main.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "e88fc719e514ffd712e97fb21587dbefd6d5860d"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3808622
project-id = 391298
