name = "WI Zoom"
filename = "WI-Zoom-1.3-MC1.18.1-rc2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3555/14/WI-Zoom-1.3-MC1.18.1-rc2.jar"
hash-format = "murmur2"
hash = "417907465"

[update]
[update.curseforge]
file-id = 3555014
project-id = 349630
