name = "Xaero's World Map"
filename = "XaerosWorldMap_1.21.2_Fabric_1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3782/705/XaerosWorldMap_1.21.2_Fabric_1.18.2.jar"
hash-format = "murmur2"
hash = "884038365"

[update]
[update.curseforge]
file-id = 3782705
project-id = 317780

[option]
optional = true
description = "adds a worldmap menu"
