name = "Xaero's World Map"
filename = "XaerosWorldMap_1.20.4.1_Fabric_1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3687/6/XaerosWorldMap_1.20.4.1_Fabric_1.18.2.jar"
hash-format = "murmur2"
hash = "1619901907"

[update]
[update.curseforge]
file-id = 3687006
project-id = 317780

[option]
optional = true
description = "adds a worldmap menu"
